Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,9 +9,12 @@ jobs:
   #       if [[ "sshpass -p $test1mode ssh ubuntu@13.58.242.170 'ls -ltr'" == 0 ]]
 
      - run: |            
+          STATUS=$?
           if [ "sshpass -p $test1mode ssh ubuntu@13.58.242.170 'ls -ltr'" == 0 ]; then
  #           sshpass -p $sanju ssh ubuntu@52.32.223.142 'ls' ;
             echo "testup1"test:
+          else
+            echo "Command '$@' exited with error status $STATUS"
           fi
         
      - run: |            
